### ISSUE TITLE
Community guidelines: add a pull request template

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/otp_builds#10]
Description should potentially include stuff like

- [ ] I read the CONTRIBUTION guidelines
- [ ] I made sure documentation is up-to-date regarding my changes
- [ ] I self-reviewed my changes

**Comment by wojtekmach** [comment]
See https://github.com/erlef/otp_builds/issues/6#issuecomment-2362122210

**Comment by paulo-ferraz-oliveira** [comment]
Same as on the other issue.

**Comment by paulo-ferraz-oliveira** [comment]
Closing as per discussion in linked pull request.
