### ISSUE TITLE
Community guidelines: add a CHANGELOG

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/otp_builds#15]
Even if the internals are just stating to go to GitHub Releases.

External tools can parse GitHub repo.s and recover this file...

**Comment by paulo-ferraz-oliveira** [comment]
I'm not sure this'll have project-specific releases (as in "tagging `otp_builds` itself), so a CHANGELOG is maybe not relevant... Feel free to close, if so.

**Comment by wojtekmach** [comment]
Yeah, I don't think we'd tag this project, especially that we have OTP-{vsn} tags to track otp.
