### ISSUE TITLE
Support macOS 15

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/otp_builds#35]
It's now available in GitHub Actions...

I've tested with compiling a couple of Erlang/OTP versions with it and found no issues yet.

**Comment by wojtekmach** [comment]
Support how? It’s already supported because we compile everything to work with at least macOS 11.0.

**Comment by paulo-ferraz-oliveira** [comment]
Maybe Support is not the best word. I meant putting it [here](https://github.com/erlef/otp_builds/pull/1/files#diff-d0777657fa3fd81d23aaf7273e58aee453b04e67882517900c56daeef9b3e4c1R52).

**Comment by wojtekmach** [comment]
In the job matrix do you want to replace macos-14? Or add another job into the matrix? The way the workflow is set up right now adding another matrix job would build and upload for arm64 _again_ which is wasteful. Replacing macos-14 runner with -15 would be fine by me but again what’s the rationale?

I could see an argument that we want to _test_ our builds on a variety of OSes/versions but I believe OTP itself is doing that anyway and so does setup-beam. So yeah not sure it’s worth it and I’d prefer to keep things minimal.

**Comment by paulo-ferraz-oliveira** [comment]
> what’s the rationale?

Backward compatibility. The more we test the merrier <sup>(*)</sup>; I'm Ok also not doing it and simply replacing 14 with 15. At least we'd know (if we're not interested in the "backward compatibility" part) that it works with more recent macOS versions (?)

If you think none of this is worth doing (that's also a choice), the issue can be closed.

---

<sup>(*)</sup> I don't know about Erlang/OTP but trust your judgement; as for `setup-beam` it's not yet using macOS runners, but the need to test this here will be diminished once it is.

**Comment by wojtekmach** [comment]
Done in 20aa008.
