### ISSUE TITLE
Community guidelines: add a bug report template

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/otp_builds#6]

**Comment by josevalim** [comment]
I would probably keep it easy for now. I think a regular template is fine. If there is enough users/issues, which I doubt, it probably makes more sense to tackle this.

**Comment by paulo-ferraz-oliveira** [comment]
Sure. An issue doesn't have to be tackled right away 😄. In any case, for me (if I'm to tackle this) it's copy-and-paste.

**Comment by wojtekmach** [comment]
I'd like to keep things low process for now, we can always add more if we get low quality issues.

**Comment by paulo-ferraz-oliveira** [comment]
I don't mind keeping things low process, but I'm not asking anybody to handle these. I'll create a very simple template.

**Comment by paulo-ferraz-oliveira** [comment]
Closing as per discussion in linked pull request.
